# docker run  --rm --name mynginx -v /opt/web/html:/var/www/html -v /opt/web/pics:/var/www/pictures -e NGINX_PORT=80 -d -p 80:80 -p 443:443 --net webnet nginx:stable

version: '3.5'
services:
  web-server:
    image: nginx:stable
    container_name: mynginx
    volumes:
      - '/opt/web/html:/var/www/html'
      - '/opt/web/pics:/var/www/pictures'
      - 'nginx-config:/var/www/config'
    environment:
      - 'NGINX_HOST=web.romnero.de'
      - 'NGINX_PORT=80'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
volumes:
  nginx-config:
networks:
  default:
    driver: bridge
    name: webnet


/----------/

# docker run --name app -p 80:80 --net appnet PHP:apache
# docker run --name app-postgres -e 'POSTGRES_PASSWORD=mypass --net appnet postgres
# docker run --name app-redis --net appnet redis

version: '3.6'
services:
  php-app:
    image: php:apache
    container_name: app
    ports:
      - '80:80'
    restart: unless-stopped
    depends-on:
      - app-db
      - app-redis
    networks:
      - internet
      - localnet
      
  app-db:
    image: postgres
    container_name: app-postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    networks:
      - localnet
      
  app-redis:
    image: redis
    container_name: app-redis
    restart: unless-stopped
    networks: 
      - localnet
      
networks:
  internet:
    name: internet
    driver: bridge
  localnet:
    name: localnet
    driver: bridge
    
      
    
    


    
