# docker run  --rm --name mynginx -v /opt/web/html:/var/www/html -v /opt/web/pics:/var/www/pictures -e NGINX_PORT=80 -d -p 80:80 -p 443:443 --net webnet nginx:stable

version: '3.5'
services:
  web-server:
    image: nginx:stable
    container_name: mynginx
    volumes:
      - '/opt/web/html:/var/www/html'
      - '/opt/web/pics:/var/www/pictures'
    environment:
      - 'NGINX_HOST=web.romnero.de'
      - 'NGINX_PORT=80'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
networks:
  default:
    driver: bridge
    name: webnet
    
    
  




    
